version: '3'
services:
    nginx:
        depends_on:
            - api
            - client
        build: ./nginx
        ports:
            - '3050:80'    
    postgres_db:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=123456@abc
    redis_db:
        image: 'redis:latest'
    # api server    
    api:
        build: ./server
        image: "prema/complex_api"   
        environment:
            - REDIS_HOST=redis_db
            - REDIS_PORT=6379
            - PGHOST=postgres_db
            - PGPORT=5432
            - PGUSER=postgres
            - PGPASSWORD=123456@abc
    #worker service
    worker:
        build: ./worker
        image: "prema/complex_worker"
        environment: 
            - REDIS_HOST=redis_db
            - REDIS_PORT=6379
     # client service
    client:
        build: ./client
        image: "prema/complex_client"  

